language: ruby
bundler_args: --without development production
sudo: false
rvm:
- 2.3.1
script:
- RAILS_ENV=test bundle exec rake db:setup spec
notifications:
  email: false
addons:
  postgresql: "9.4"
